before:
  hooks:
    - go mod tidy
builds:
  - main: ./main.go
    id: livego
    binary: livego
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm
